name: Run Integration Tests on pull request in main branch

on:
  push:
    branches:
      - "ci/**"             
  pull_request:
    branches:
      - main      
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          cache: 'maven'
            
      - name: Run unit tests
        run: ./mvnw clean integration-test
